apiVersion: v1
kind: Secret
metadata:
  name: ecom-secrets
  labels:
    app: ecom
type: Opaque   # Generic Secret storing your own key-value config
stringData:
  RABBITMQ_USERNAME: "qutgvjpf"
  RABBITMQ_PASSWORD: "BqLdO3kp1SdY_GAQm_KBq0m3AKdQEyq5"
  RABBITMQ_VHOST: "qutgvjpf"
  DB_USER: "sachin"
  DB_PASS: "Sachin@2247"
  CLOUD_API_KEY: "726389767127975"
  CLOUD_API_SECRET: "4gskpmgkD-3gpaevB8UShnTC7hE"
  SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"